apiVersion: apps/v1
kind: Deployment
metadata:
  name: vehicle-api
  namespace: carlog-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vehicle-api
  template:
    metadata:
      labels:
        app: vehicle-api
    spec:
      containers:
        - name: vehicle-api
          image: carlogvehicleapi:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: vehicle-api-config
            - secretRef:
                name: vehicle-api-secret
          resources:
            requests: { memory: "256Mi", cpu: "250m" }
            limits: { memory: "512Mi", cpu: "500m" }
